http:
  routers:
    mc-files-router:
      entryPoints:
        - websecure
      rule: "Host(`files.mc.kdecosta.com`)"
      service: mc-files-service
      tls:
        certResolver: myresolver

    game-server-panel-router:
      entryPoints:
        - websecure
      rule: "Host(`game-panel.kdecosta.com`)"
      service: game-server-panel-service
      tls:
        certResolver: myresolver

    game-server-daemon-router:
      entryPoints:
        - mcsdaemon
      rule: "Host(`game-panel.kdecosta.com`)"
      service: game-server-daemon-service
      tls:
        certResolver: myresolver

    jfin99:
      entryPoints:
        - websecure
      rule: "Host(`jfin99.svc.home.arpa`)"
      service: jfin99-service
      tls:
        certResolver: myresolver

    dns:
      entryPoints:
        - websecure
      rule: "Host(`dns.svc.home.arpa`)"
      service: dns-service
      tls:
        certResolver: myresolver

  services:
    dns-service:
      loadBalancer:
        servers:
          - url: "http://dns.home.arpa:5380/"

    jfin99-service:
      loadBalancer:
        servers:
          - url: "http://newfie.home.arpa:8096/"

    mc-files-service:
      loadBalancer:
        servers:
          - url: "http://games1.lab.home.arpa:8080"

    game-server-panel-service:
      loadBalancer:
        servers:
          - url: "http://games1.lab.home.arpa:23335"

    game-server-daemon-service:
      loadBalancer:
        servers:
          - url: "http://games1.lab.home.arpa:24444"

