entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  mcsdaemon:
    address: ":24444"

api:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /routes.yml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: kalinduk.decosta@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  filePath: "/log/error.log"
  format: json

accessLog:
  filePath: "/log/access.log"
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep
