site_name: Kalindu's Homelab Docs
site_url: https://kdecosta.com/
site_author: kalindudc

copyright: Copyright &copy; 2023 Kalindu De Costa, All rights reserved

repo_url: https://github.com/kalindudc/homelab
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - The Lab: lab.md
  - Network:
    - network/index.md
    - network/vlans.md
    - network/bypass_bell_homehub.md
  - Services:
    - services/index.md
    - services/proxmox.md
    - services/kubernetes.md
  - Automation:
    - automation/index.md
    - automation/ansible.md
    - automation/terraform.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share

plugins:
  - search
  - git-revision-date
  - macros

markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs
