site_name: Kalindu's Homelab Docs
site_url: https://kdecosta.com/
site_author: kalindudc

copyright: Copyright &copy; 2023 Kalindu De Costa, All rights reserved

repo_url: https://github.com/kalindudc/homelab
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - The Lab: lab.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation bette

plugins:
  - search
  - git-revision-date
  - macros

markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs
