site_name: Kalindu's Homelab Docs
site_url: https://kdecosta.com/
site_author: kalindudc

copyright: Copyright &copy; 2023 Kalindu De Costa, All rights reserved

repo_url: https://github.com/kalindudc/homelab
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - The Lab:
    - lab/index.md
    - Updates:
      - lab/updates/update_20230324.md
  - Network:
    - network/index.md
    - network/bypass_bell_homehub.md
  # - Services: []
  # - Automation: []

extra_css:
  - css/extra.css

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share
    - toc.follow
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date
  - macros
  - tags

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
