---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/src/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/src/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/src/terraform"

dotenv: [".env"]

env:
  KUBECONFIG: "~/.kube/homelab.config"

tasks:

  init:
    desc: Initialize mac workstation dependencies
    cmds:
      - scripts/install-base.sh
      - scripts/install-mac.sh

  init-linux:
    desc: Initialize linux workstation dependencies
    cmds:
      - scripts/install-base.sh
      - scripts/install.sh

  sync_hass:
    desc: Call sync_hass ansible playbook
    cmds:
      - ansible-playbook -i src/ansible/inventory/hass.ini src/ansible/playbooks/sync_hass.yml

  edit_vault:
    desc: Edit ansible vault
    cmds:
      - ansible-vault edit src/ansible/playbooks/vault.yml

  view_vault:
    desc: View ansible vault
    cmds:
      - ansible-vault view src/ansible/playbooks/vault.yml
