---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/src/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/src/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/src/terraform"

dotenv: [".env"]

env:
  KUBECONFIG: "~/.kube/homelab.config"

tasks:

  init:
    desc: Initialize mac workstation dependencies
    cmds:
      - scripts/install-base.sh
      - scripts/install-mac.sh

  init-linux:
    desc: Initialize linux workstation dependencies
    cmds:
      - scripts/install-base.sh
      - scripts/install.sh
      - cat src/known_hosts.txt | xargs -I {} ssh-keyscan {} >> ~/.ssh/known_hosts

  init-nix:
    desc: Initialize for NixOS
    cmds:
      - echo "NixOS cannot be managed from this repo"
      - echo "See the dependencies section in README.md"

  sync_known_hosts:
    desc: Add all servers to known-hosts
    cmds:
      - cat src/known_hosts.txt | xargs -I {} ssh-keyscan {} >> ~/.ssh/known_hosts

  sync_hass:
    desc: Call sync_hass ansible playbook
    cmds:
      - ansible-playbook -i src/ansible/inventory/hass.ini src/ansible/playbooks/sync_hass.yml

  edit_vault:
    desc: Edit ansible vault
    cmds:
      - ansible-vault edit src/ansible/playbooks/vault.yml

  view_vault:
    desc: View ansible vault
    cmds:
      - ansible-vault view src/ansible/playbooks/vault.yml
