version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - type: bind
        source: /home/jellyfin/mnt
        target: /media
        bind:
          propagation: rshared
      - /usr/share/jellyfin:/usr/share/jellyfin
      - ./jellyfin.sh:/home/jellyfin/jellyfin.sh:ro
    environment:
      - PUID=109
      - PGID=112
    user: "109:112"
    entrypoint: ["/bin/bash", "/home/jellyfin/jellyfin.sh"]
