---
- hosts: all
  become: yes
  tasks:
  - name: "update and upgrade"
    become: yes
    ignore_errors: yes
    failed_when: "'FAILED' in command_result.stderr"
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: Enable service nginx and ensure it is not masked
    ansible.builtin.systemd:
      name: nginx
      enabled: true
      masked: no
    notify: restart nginx

  - name: Make sure nginx service unit is running
    ansible.builtin.systemd:
      state: started
      name: nginx
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
