#! /usr/bin/env python3
import json
import os

CURR_DIR = os.path.dirname(os.path.realpath(__file__))
TF_DIR = f"{os.path.abspath(os.path.join(CURR_DIR, '../'))}/terraform/proxmox"

def main():

  print("Syncing data...\n")
  print("Reading hosts.json...\n")
  hosts = {}
  with open(f"{CURR_DIR}/hosts.json") as f:
    hosts = json.load(f)

  ### Build for terraform
  print(f"Building terraform locals in {TF_DIR}/locals.tf.json...")
  tf_locals = {"locals": hosts}
  with open(f"{TF_DIR}/locals.tf.json", "w") as f:
    json.dump(tf_locals, f, indent=2)

  ### Build for ansible


if __name__ == "__main__":
  main()
